rename "01 什么是多线程？" "01 什么是多线程？"
rename "02 多线程api详解（一）" "02 多线程api详解（一）"
rename "03 多线程API详解（二） [高质量].mp3" "03 多线程API详解（二） "
rename "04 多线程API详解（三） [高质量].mp3" "04 多线程API详解（三） "
rename "05 多线程模拟火车站售票 [高质量].mp3" "05 多线程模拟火车站售票 "
rename "06 多线程的同步和互斥 [高质量].mp3" "06 多线程的同步和互斥 "
rename "07 多线程同步-临界区CriticalSection [高质量].mp3" "07 多线程同步-临界区CriticalSection "
rename "08 多线程同步-线程死锁 [高质量].mp3" "08 多线程同步-线程死锁 "
rename "09 多线程同步-信号量Semaphore [高质量].mp3" "09 多线程同步-信号量Semaphore "
rename "10 多线程同步-互斥量Mutex [高质量].mp3" "10 多线程同步-互斥量Mutex "
rename "11 多线程同步-事件Event [高质量].mp3" "11 多线程同步-事件Event "
rename "12 多线程同步-PV操作 [高质量].mp3" "12 多线程同步-PV操作 "
rename "13 多线程同步总结 [高质量].mp3" "13 多线程同步总结 "
rename "14 线程本地存储（TLS） [高质量].mp3" "14 线程本地存储（TLS） "
rename "15 多线程间消息通讯 [高质量].mp3" "15 多线程间消息通讯 "
rename "16 C++11多线程简介 [高质量].mp3" "16 C++11多线程简介 "
rename "17 线程thread类 [高质量].mp3" "17 线程thread类 "
rename "18 this_thread命名空间 [高质量].mp3" "18 this_thread命名空间 "
rename "19 原子atomic类、atomic_flag类 [高质量].mp3" "19 原子atomic类、atomic_flag类 "
rename "20 互斥mutex类、recursive_mutex类等 [高质量].mp3" "20 互斥mutex类、recursive_mutex类等 "
rename "21 锁管理lock_guard类 [高质量].mp3" "21 锁管理lock_guard类 "
rename "22 锁管理unique_lock类 [高质量].mp3" "22 锁管理unique_lock类 "
rename "23 条件变量conditon_variable类 [高质量].mp3" "23 条件变量conditon_variable类 "
rename "24 future类 [高质量].mp3" "24 future类 "
rename "25 promise类 [高质量].mp3" "25 promise类 "
rename "26 packaged_task类 [高质量].mp3" "26 packaged_task类 "
rename "27 future、promise、packaged_task等 [高质量].mp3" "27 future、promise、packaged_task等 "
